# Moses Permaul - IS362 - Project 2 - Wide Data 3

This data set contains some statistics and details on daily trending YouTube videos for the US. The data keeps track of various statistics such as likes and dislikes, comments, and descriptions. The data is daily details, so there is a large amount of data.

Some analysis that can be performed is to find out what videos are trending the longest and how the rate of likes and or dislikes increases the longer a video is on the trending list. 

After cleaning this data, we will find the following:
1. What videos are trending the longest
2. The rate of likes and/or dislikes the longer a video is trending

### Python Code for Imports and Reading the Data
To begin, we will import the standard libraries needed, read in the data, and display the first 5 rows.

In [2]:
# standard imports for numpy and pandas
import numpy as np
import pandas as pd

# read wide data to DataFrame
raw_data = pd.read_csv('data/wide_data_3.csv')

# make a copy of DataFrame to preserve origanal import
wide_data = raw_data.copy()

# view first 5 rows to understand the data
wide_data.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...

### Cleaning the Data
In order to answer our questions, we won't need the majority of the columns currently in the DataFrame. We will start by removing the ones we don't need.

In [3]:
# wide_data[wide_data.title == 'WE WANT TO TALK ABOUT OUR MARRIAGE']

# get column list
wide_data.columns

# delete columns not neede
wide_data.drop(columns=['category_id', 'publish_time', 'tags', 'views', 'comment_count', 'thumbnail_link', 
                        'comments_disabled', 'ratings_disabled','video_error_or_removed', 'description'], inplace=True)

# view first 5 rows
wide_data.head()

,video_id,trending_date,title,channel_title,likes,dislikes
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,57527,2966
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,97185,6146
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,146033,5339
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,10172,666
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,132235,1989

We will now look at the data types within the "wide_data" DataFrame in order to make sure that we have the right data types.

In [4]:
# view data types for the DataFrame
wide_data.dtypes

video_id         object
trending_date    object
title            object
channel_title    object
likes             int64
dislikes          int64
dtype: object

The first thing that we notice is that the column "**treding_date**" is a string and not date.To clean this, we will **convert** it to datetime.

In [5]:
# convert the 'trending_date' column to datetime format, errors param set to 'coerce'
wide_data['trending_date'] = pd.to_datetime(wide_data['trending_date'], format='%y.%d.%m', errors='coerce')

# view first 5 rows
wide_data.head()

,video_id,trending_date,title,channel_title,likes,dislikes
0,2kyS6SvSYSE,2017-11-14,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,57527,2966
1,1ZAPwfrtAFY,2017-11-14,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,97185,6146
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,146033,5339
3,puqaWrEC7tY,2017-11-14,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,10172,666
4,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,132235,1989

Looking at the data types now, we should now have clean data to work with.

In [6]:
# view data types for the DataFrame
wide_data.dtypes

video_id                 object
trending_date    datetime64[ns]
title                    object
channel_title            object
likes                     int64
dislikes                  int64
dtype: object

### Analyzing the Data

1. What videos are trending the longest?

    To find this, we will create a new dataframe that stores each title and a count of the title's video id. The count of the video id will let us know how any days the title has been trending for.

In [7]:
# create DataFrame that has the video titles and count video_id
df_count = wide_data.groupby(['title']).agg(['count'])['video_id']

# use nlargest on count to view top 10
df_count.nlargest(10, 'count')

                                                    count
title
WE MADE OUR MOM CRY...HER DREAM CAME TRUE!             30
Charlie Puth - BOY [Official Audio]                    29
Mission: Impossible - Fallout (2018) - Official...     29
Rooster Teeth Animated Adventures - Millie So S...     29
Sam Smith - Pray (Official Video) ft. Logic            29
The ULTIMATE $30,000 Gaming PC Setup                   29
Why I'm So Scared (being myself and crying too ...     29
YoungBoy Never Broke Again Goes Sneaker Shoppin...     29
Bohemian Rhapsody | Teaser Trailer [HD] | 20th ...     28
Cobra Kai Season 2                                     28

Looking at the data, we can see that the title "**WE MADE OUR MOM CRY...HER DREAM CAME TRUE!**" trended the longest. It was on the list for 30 different days

2. The rate of likes and/or dislikes the longer a video is trending.

Since the ***data contains the over 6455 unique titles***:

```python
wide_data['title'].nunique()
```
We are going to focus on only the top title.

In [8]:
# create DataFrame with data from most trending video
df_top = wide_data.loc[wide_data['title'] == 'WE MADE OUR MOM CRY...HER DREAM CAME TRUE!']

# update DataFrame with sort values on trending date
df_top = df_top.sort_values('trending_date')

In [9]:
# view full dataframe
df_top

,video_id,trending_date,title,channel_title,likes,dislikes
34550,j4KvrAUjn6c,2018-05-14,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,54280,4696
34752,j4KvrAUjn6c,2018-05-15,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,77378,12160
34901,j4KvrAUjn6c,2018-05-15,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,77378,12160
34966,j4KvrAUjn6c,2018-05-16,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,90451,14792
35180,j4KvrAUjn6c,2018-05-17,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,101461,16170
35396,j4KvrAUjn6c,2018-05-18,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,110373,17131
35600,j4KvrAUjn6c,2018-05-19,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,116508,17787
35804,j4KvrAUjn6c,2018-05-20,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,121673,18323
36035,j4KvrAUjn6c,2018-05-21,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,125317,18633
36245,j4KvrAUjn6c,2018-05-22,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,128377,18901
36453,j4KvrAUjn6c,2018-05-23,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,130906,19082
36661,j4KvrAUjn6c,2018-05-24,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,133189,19203
36868,j4KvrAUjn6c,2018-05-25,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,135425,19324
37080,j4KvrAUjn6c,2018-05-26,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,137831,19469
37291,j4KvrAUjn6c,2018-05-27,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,139338,19559
37493,j4KvrAUjn6c,2018-05-28,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,140940,19645
37694,j4KvrAUjn6c,2018-05-29,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,142441,19706
37899,j4KvrAUjn6c,2018-05-30,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,143957,19784
38108,j4KvrAUjn6c,2018-05-31,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,146110,19887
38307,j4KvrAUjn6c,2018-06-01,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,146847,19925
38510,j4KvrAUjn6c,2018-06-02,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,148140,19980
38715,j4KvrAUjn6c,2018-06-03,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,149538,20048
38918,j4KvrAUjn6c,2018-06-04,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,151029,20123
39122,j4KvrAUjn6c,2018-06-05,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,152552,20232
39326,j4KvrAUjn6c,2018-06-06,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,154861,20398
39529,j4KvrAUjn6c,2018-06-07,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,156308,20494
39731,j4KvrAUjn6c,2018-06-08,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,158478,20617
39937,j4KvrAUjn6c,2018-06-09,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,160160,20717
40146,j4KvrAUjn6c,2018-06-10,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,162696,20861
40346,j4KvrAUjn6c,2018-06-11,WE MADE OUR MOM CRY...HER DREAM CAME TRUE!,Lucas and Marcus,163325,20892

In [10]:
# add column for percent change in likes
df_top['pct_like_change'] = df_top['likes'].pct_change()

# add column for percent change in dislikes
df_top['pct_dislikes_change'] = df_top['dislikes'].pct_change()

Using the percent change in likes, we will view first 5 days which had the biggest percent increase.

In [11]:
# sort dataframe by pct_like_change
df_top = df_top.sort_values('pct_like_change', ascending=False)

# view first 5 rows
df_top[['trending_date', 'likes', 'dislikes', 'pct_like_change']].head()

      trending_date   likes  dislikes  pct_like_change
34752    2018-05-15   77378     12160         0.425534
34966    2018-05-16   90451     14792         0.168950
35180    2018-05-17  101461     16170         0.121723
35396    2018-05-18  110373     17131         0.087837
35600    2018-05-19  116508     17787         0.055584

Using the percent change in dislikes we will view first 5 days which had the biggest percent increase.

In [12]:
# sort dataframe by pct_like_change
df_top = df_top.sort_values('pct_dislikes_change', ascending=False)

# view first 5 rows
df_top[['trending_date', 'likes', 'dislikes', 'pct_dislikes_change']].head()

      trending_date   likes  dislikes  pct_dislikes_change
34752    2018-05-15   77378     12160             1.589438
34966    2018-05-16   90451     14792             0.216447
35180    2018-05-17  101461     16170             0.093158
35396    2018-05-18  110373     17131             0.059431
35600    2018-05-19  116508     17787             0.038293

Looking at the results from both percentages, we can see that biggest changes happened at the beginning of the trending period. The rate of change for dislikes were higher at some points, the number of likes were higher overall.